### ISSUE TITLE
PROYECTO FINAL 

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/actividad-11-proyecto-final-de-realidad-aumentada-equipo-magaly#1]
[PROYECTO FINAL ITSMO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-11-proyecto-final-de-realidad-aumentada-equipo-magaly/files/15457157/PROYECTO.FINAL.ITSMO.pdf)

**Comment by josealfredo79** [comment]
Proyecto final Calificacion 58..falta ver la app y la documentacion...
